### ISSUE TITLE
Blacklist Mode?

### ISSUE THREAD

**Issue by woliver99** [2008Choco/VeinMiner#104] opened 2024-01-10 19:25 UTC
Is there any way you could add a blacklist mode to the plugin? Because I don't want to add every single block to the config.

**Comment by 2008Choco** [comment] 2024-02-05 03:28
This can probably be classified as a duplicate of #95, so I'll close this issue as such.

With that being said, I don't think you're actually going to want a blacklist mode. You'll realize fairly quickly that your blacklist won't provide much more benefit over the current list functionality. I think the appropriate solution is really just allowing for tags in the block list, which is planned.

**Closed** 2024-02-05 03:28 UTC
Labels: duplicate, enhancement
